"""Unit tests for backend/src/engine/equity.py.

Tests the engine's three core surfaces:
- ``hand_type_from_cards`` — concrete cards -> canonical 169-type string
- ``preflop_equity_lookup`` / ``preflop_equity_vs_range`` — instant table reads
- ``equity_vs_hand`` / ``equity_vs_range`` — vectorized live evaluation

Postflop tests anchor on **river** boards because exhaustive evaluation over a
single completion gives an exact answer (no Monte Carlo noise). Preflop tests
use loose tolerance bands against published reference equities since the
lookup table itself was generated by Monte Carlo.

Run from backend/: pytest tests/test_equity.py
"""

import pytest

from src.engine.equity import (
    equity_vs_hand,
    equity_vs_range,
    hand_type_from_cards,
    preflop_equity_lookup,
    preflop_equity_vs_range,
)
from src.engine.variables import handsList, rangeHands


def _legacy_combo_to_card_ids(combo: list[tuple[int, int]]) -> tuple[int, int]:
    """Convert a [(rank_1based, suit_1based), ...] combo to (id0, id1).

    Mirrors the encoding in engine.cards.encode_card.
    """
    (r0, s0), (r1, s1) = combo
    return (r0 - 1) * 4 + (s0 - 1), (r1 - 1) * 4 + (s1 - 1)


# ---------------------------------------------------------------------------
# hand_type_from_cards
# ---------------------------------------------------------------------------

def test_hand_type_round_trip_all_169() -> None:
    """Every one of the 169 hand types round-trips through hand_type_from_cards.

    For each canonical type, take the first concrete combo from
    ``rangeHands[type]`` and confirm classification returns the same type.
    Catches encoding bugs across all rank/suit permutations.
    """
    for ht in handsList:
        combo = rangeHands[ht][0]
        c0, c1 = _legacy_combo_to_card_ids(combo)
        result = hand_type_from_cards(c0, c1)
        assert result == ht, (
            f"Round-trip failed: {ht} -> combo {combo} -> {result}"
        )


def test_hand_type_is_order_independent() -> None:
    """hand_type_from_cards always sorts the higher rank first."""
    # 7c = rank index 5 (zero-based), suit index 0 -> id 20
    seven_clubs = 5 * 4 + 0
    # Ac = rank index 12, suit index 0 -> id 48
    ace_clubs = 12 * 4 + 0
    assert hand_type_from_cards(seven_clubs, ace_clubs) == "A7s"
    assert hand_type_from_cards(ace_clubs, seven_clubs) == "A7s"


# ---------------------------------------------------------------------------
# Preflop lookup table
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "hero,villain,expected,tol",
    [
        ("AA", "KK", 0.815, 0.015),  # textbook ~81.5%
        ("AA", "QQ", 0.815, 0.015),
        ("KK", "QQ", 0.815, 0.015),
        ("AKo", "22", 0.475, 0.020),  # near-coinflip; small pair has slight edge
        ("AKs", "QQ", 0.460, 0.020),  # AKs vs an overpair is ~46%
        ("AKs", "AA", 0.120, 0.020),  # dominated by AA blockers
        ("72o", "AA", 0.120, 0.025),  # close-to-worst preflop matchup
    ],
)
def test_preflop_equity_lookup_known_values(
    hero: str, villain: str, expected: float, tol: float,
) -> None:
    """Lookup table matches widely-published reference equities."""
    result = preflop_equity_lookup(hero, villain)
    assert abs(result["equity"] - expected) < tol, (
        f"{hero} vs {villain}: got {result['equity']:.4f}, "
        f"expected {expected} +/- {tol}"
    )
    # Probabilities partition the outcome space.
    assert abs(result["win"] + result["tie"] + result["lose"] - 1.0) < 1e-9


def test_preflop_equity_vs_range_returns_by_hand_breakdown() -> None:
    """Per-hand-type equity breakdown is populated and well-formed.

    AKs equity stratifies as expected against an overpair ladder:
    - vs AA: heavily dominated (~12%, both ace blockers gone for hero outs)
    - vs KK: less dominated (~34%; ace outs live, plus straight/flush draws)
    - vs QQ: near-coinflip (~46%; both overcards live)
    """
    result = preflop_equity_vs_range("AKs", ["AA", "KK", "QQ"])
    assert set(result["by_hand"].keys()) == {"AA", "KK", "QQ"}
    assert result["by_hand"]["AA"] < 0.20
    assert 0.30 < result["by_hand"]["KK"] < 0.40
    assert 0.40 < result["by_hand"]["QQ"] < 0.50


def test_preflop_lookup_vs_monte_carlo_agreement() -> None:
    """Lookup table agrees with live Monte Carlo when blockers don't apply.

    The lookup table averages by total combo counts (always 6 for pairs);
    the live function reduces combo counts when the hero blocks villain
    cards. To compare apples-to-apples we pick a villain range that shares
    no ranks with the hero — AKs vs JJ/TT/99 — so combo counts match
    between the two paths and the only remaining gap is Monte Carlo noise.
    """
    hero_cards = ["As", "Ks"]
    villain_range = ["JJ", "TT", "99"]

    lookup_result = preflop_equity_vs_range("AKs", villain_range)
    mc_result = equity_vs_range(hero_cards, villain_range, n_samples=4000)

    diff = abs(lookup_result["equity"] - mc_result["equity"])
    assert diff < 0.02, (
        f"Lookup {lookup_result['equity']:.4f} vs "
        f"MC {mc_result['equity']:.4f} differ by {diff:.4f}"
    )


# ---------------------------------------------------------------------------
# equity_vs_hand — exact answers on river boards
# ---------------------------------------------------------------------------

def test_river_royal_vs_set_exact() -> None:
    """Hero makes a royal flush on the river — equity must be exactly 1.0."""
    # Hero: As Ks; Board: Qs Js Ts 2c 3d -> royal flush in spades.
    # Villain: Qc Qd makes a set of queens.
    result = equity_vs_hand(
        ["As", "Ks"], ["Qc", "Qd"],
        board=["Qs", "Js", "Ts", "2c", "3d"],
    )
    assert result["equity"] == 1.0
    assert result["win"] == 1.0
    assert result["lose"] == 0.0


def test_river_set_loses_to_flush_exact() -> None:
    """Hero has trips, villain has a flush — equity must be exactly 0.0."""
    # Hero: 7c 7d; Board: 7s Ts 2s 3s 9h -> trip sevens for hero, but
    # villain As Ks plus three board spades = ace-high flush.
    result = equity_vs_hand(
        ["7c", "7d"], ["As", "Ks"],
        board=["7s", "Ts", "2s", "3s", "9h"],
    )
    assert result["equity"] == 0.0
    assert result["lose"] == 1.0
    assert result["win"] == 0.0


def test_river_board_plays_full_tie() -> None:
    """Both seats play the board straight — equity must be exactly 0.5."""
    # Board 9c Tc Js Qd Kh is a king-high straight. Neither hero (2c 3d)
    # nor villain (2h 3s) has a card that beats the board, so both play
    # the same 5-card straight from the community.
    result = equity_vs_hand(
        ["2c", "3d"], ["2h", "3s"],
        board=["9c", "Tc", "Js", "Qd", "Kh"],
    )
    assert result["tie"] == 1.0
    assert result["equity"] == 0.5
    assert result["win"] == 0.0


# ---------------------------------------------------------------------------
# equity_vs_hand / equity_vs_range — preflop Monte Carlo paths
# ---------------------------------------------------------------------------

def test_equity_vs_hand_preflop_aa_vs_kk_monte_carlo() -> None:
    """Live preflop AA-vs-KK lands in the textbook 0.79-0.84 band."""
    result = equity_vs_hand(
        ["As", "Ad"], ["Ks", "Kd"],
        board=None,
        n_samples=5000,
    )
    assert 0.79 < result["equity"] < 0.84, (
        f"AA vs KK preflop = {result['equity']:.4f} (expected ~0.81)"
    )
    # Probabilities partition the outcome space.
    assert abs(
        result["win"] + result["tie"] + result["lose"] - 1.0
    ) < 1e-9


def test_equity_vs_range_postflop_river_exact() -> None:
    """Hero with the nuts on the river beats every hand in a strong range."""
    # Hero As Ks on Qs Js Ts 2c 3d -> royal flush. Villain range is sets and
    # two pair candidates that all lose to the royal.
    result = equity_vs_range(
        ["As", "Ks"], ["QQ", "JJ", "TT"],
        board=["Qs", "Js", "Ts", "2c", "3d"],
    )
    assert result["equity"] == 1.0
    assert set(result["by_hand"].keys()) == {"QQ", "JJ", "TT"}
    for ht in ("QQ", "JJ", "TT"):
        assert result["by_hand"][ht] == 1.0
